name: Deploy to Hugging Face Spaces

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Push to Hugging Face Spaces
        env:
          HG: ${{ secrets.HG}}
        run: |
          git remote add huggingface https://groundhog2107:$HG@huggingface.co/spaces/groundhog2107/demoText
          git push huggingface main --force
